=== ShinjiEva02/grsu-html-xml/lab3/autoshop.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- определение простых элементов -->
  <xs:element name="mark" type="xs:string"/>
  <xs:element name="color" type="xs:string"/>
  <xs:element name="type" type="xs:string"/>
  <xs:element name="age" type="xs:integer"/>
  <xs:element name="price" type="xs:integer"/>
  <xs:element name="capacity" type="xs:decimal"/>

  <!-- определение атрибутов -->
  <xs:attribute name="state" type="xs:string" default="new"/>
  <!-- определение составных элементов -->
  <xs:element name="auto">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mark"/>
        <xs:element ref="color"/>
        <xs:element ref="type"/>
        <xs:element ref="age"/>
        <xs:element ref="price"/>
        <xs:element ref="capacity"/>
      </xs:sequence>
      <xs:attribute ref="state" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="autoshop">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="auto" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ShinjiEva02/grsu-html-xml/lab3/autoshop.xml
<?xml version="1.0" encoding="UTF-8"?>
<autoshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="autoshop.xsd">
  <auto state="used">
    <mark>Opel</mark>
    <color>Blue</color>
    <type>Wagon</type>
    <age>2007</age>
    <price>7000</price>
    <capacity>1.2</capacity>
  </auto>
  <auto state="new">
    <mark>Ferrari</mark>
    <color>Silver</color>
    <type>Uvinersal</type>
    <age>2018</age>
    <price>1000000</price>
    <capacity>1.6</capacity>
  </auto>
  <auto state="used">
    <mark>Honda</mark>
    <color>Black</color>
    <type>Wagon</type>
    <age>2005</age>
    <price>12000</price>
    <capacity>1.9</capacity>
  </auto>
  <auto state="new">
    <mark>Mersedes</mark>
    <color>Lime</color>
    <type>Hatchback</type>
    <age>2018</age>
    <price>250000</price>
    <capacity>1.8</capacity>
  </auto>
  <auto state="used">
    <mark>Scoda</mark>
    <color>4000</color>
    <type>Universal</type>
    <age>2003</age>
    <price>2000</price>
    <capacity>2.2</capacity>
  </auto>
</autoshop>
